### ISSUE TITLE
Changes within gcc/emit-rtl.c

### ISSUE THREAD

**Issue by ghost** [saaadhu/gcc-avr-cc0#1]
Does the modifed avr-backend depend on the change within the non-backend file `gcc/emit-rtl.c`?

https://github.com/saaadhu/gcc-avr-cc0/commit/53b9401f0afe1f8cd679b982ecca1d3332ea2c37#diff-2b4dff67236e3e1ab85ce55c5ce64fe3729cc5ad4d1a6c82eea99dd3ef5fe030

**Comment by saaadhu** [comment]
Yes, but that change is already upstream. I committed it back in August (https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=e7d55c6b81733335d81e35f7c0116bbdffccb682)

**Comment by ghost** [comment]
All good then.
